### ISSUE TITLE
Bug "malloc: *** error for object 0x70005f9c03: pointer being freed was not allocated"

### ISSUE THREAD

**Issue by chrismwendt** [dfinity/wasmtime-hs#45]
There appears to be a bug where if you call `wat2wasm` a zillion times in a row it crashes.

Minimal example:

```haskell
module Main (main) where

import Control.Exception
import Control.Monad
import Wasmtime
import Data.ByteString.Char8 qualified as BC

main :: IO ()
main = forM_ [0 ..] $ \i -> do
  when (i `mod` 100 == 0) $ do
    putStrLn $ "Try #" ++ show i

  either throwIO pure $ wat2wasm $ BC.pack "(module)"
```

```cabal
cabal-version: 1.12

name: haskell-wasmtime-sandbox
version: 0.0.0
build-type: Simple

executable haskell-wasmtime-sandbox
  main-is: Main.hs
  ghc-options: -O0
  build-depends:
    base, wasmtime-hs, bytestring
  extra-libraries: wasmtime
  default-language: GHC2021
```

Error:

```
$ cabal run
Try #0
Try #100
...
Try #4500
haskell-wasmtime-sandbox(10139,0x1dcc6f280) malloc: *** error for object 0x70005f9c03: pointer being freed was not allocated
haskell-wasmtime-sandbox(10139,0x1dcc6f280) malloc: *** set a breakpoint in malloc_error_break to debug
$ 
```

When I run with `-O1` (as opposed to `-O0` in the example above) then I do not get the error.

Any ideas how to debug this?

- wasmtime version https://github.com/bytecodealliance/wasmtime/tree/a45abadbc39a57dd3e404231e2751a80cdafa4b0
- wasmtime-hs https://github.com/dfinity/wasmtime-hs/tree/a2ba70ef58cac6a83276cdd7747934a256d2dbfe
- GHC 9.2.8
- cabal-install 3.10.1.0
- Mac M1 Sonoma 14.0

**Comment by michael-weigelt** [comment]
Thank you for raising this issue. I have proposed a fix, and hopefully we'll catch any similar issues while we are at it.
